/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	{
		"ddr4_ddr4_0_C0_DDR4_ADDRESS_BLOCK",
		"ddr4_ddr4_0",
		0x000400000000,
		2147483648,
	},
	{
		"ddr4_ddr4_1_C0_DDR4_ADDRESS_BLOCK",
		"ddr4_ddr4_1",
		0x000480000000,
		2147483648,
	},
	{
		"psu_ddr_0_MEM_0",
		"psu_ddr_0",
		0x40000000,
		1073741824,
	},
	/* psu_ocm_ram_0_MEM_0 memory will not be tested since application resides in the same memory */
};

int n_memory_ranges = 3;
